<option value="1">WOW US / Aegwynn</option>
<option value="2">WOW US / Aerie Peak</option>
<option value="3">WOW US / Agamaggan</option>
<option value="4">WOW US / Aggramar</option>
<option value="5">WOW US / Akama</option>
<option value="6">WOW US / Alexstrasza</option>
<option value="7">WOW US / Alleria</option>
<option value="8">WOW US / Altar of Storms</option>
<option value="9">WOW US / Alterac Mountains</option>
<option value="10">WOW US / Aman'Thul</option>
<option value="11">WOW US / Andorhal</option>
<option value="12">WOW US / Anetheron</option>
<option value="13">WOW US / Antonidas</option>
<option value="14">WOW US / Anub'arak</option>
<option value="15">WOW US / Anvilmar</option>
<option value="16">WOW US / Arathor</option>
<option value="17">WOW US / Archimonde</option>
<option value="18">WOW US / Area 52</option>
<option value="19">WOW US / Argent Dawn</option>
<option value="20">WOW US / Arthas</option>
<option value="21">WOW US / Arygos</option>
<option value="22">WOW US / Auchindoun</option>
<option value="23">WOW US / Azgalor</option>
<option value="24">WOW US / Azjol-Nerub</option>
<option value="635">WOW US / Azralon</option>
<option value="25">WOW US / Azshara</option>
<option value="26">WOW US / Azuremyst</option>
<option value="27">WOW US / Baelgun</option>
<option value="28">WOW US / Balnazzar</option>
<option value="29">WOW US / Barthilas</option>
<option value="30">WOW US / Black Dragonflight</option>
<option value="31">WOW US / Blackhand</option>
<option value="32">WOW US / Blackrock</option>
<option value="33">WOW US / Blackwater Raiders</option>
<option value="34">WOW US / Blackwing Lair</option>
<option value="35">WOW US / Blade's Edge</option>
<option value="36">WOW US / Bladefist</option>
<option value="37">WOW US / Bleeding Hollow</option>
<option value="38">WOW US / Blood Furnace</option>
<option value="39">WOW US / Bloodhoof</option>
<option value="40">WOW US / Bloodscalp</option>
<option value="41">WOW US / Bonechewer</option>
<option value="550">WOW US / Borean Tundra</option>
<option value="481">WOW US / Borean Tundra</option>
<option value="42">WOW US / Boulderfist</option>
<option value="43">WOW US / Bronzebeard</option>
<option value="44">WOW US / Burning Blade</option>
<option value="45">WOW US / Burning Legion</option>
<option value="46">WOW US / Caelestrasz</option>
<option value="47">WOW US / Cairne</option>
<option value="48">WOW US / Cenarion Circle</option>
<option value="49">WOW US / Cenarius</option>
<option value="50">WOW US / Cho'gall</option>
<option value="51">WOW US / Chromaggus</option>
<option value="52">WOW US / Coilfang</option>
<option value="53">WOW US / Crushridge</option>
<option value="54">WOW US / Daggerspine</option>
<option value="55">WOW US / Dalaran</option>
<option value="56">WOW US / Dalvengyr</option>
<option value="57">WOW US / Dark Iron</option>
<option value="58">WOW US / Darkspear</option>
<option value="59">WOW US / Darrowmere</option>
<option value="60">WOW US / Dath'Remar</option>
<option value="551">WOW US / Dawnbringer</option>
<option value="473">WOW US / Dawnbringer</option>
<option value="61">WOW US / Deathwing</option>
<option value="62">WOW US / Demon Soul</option>
<option value="63">WOW US / Dentarg</option>
<option value="64">WOW US / Destromath</option>
<option value="65">WOW US / Dethecus</option>
<option value="66">WOW US / Detheroc</option>
<option value="67">WOW US / Doomhammer</option>
<option value="68">WOW US / Draenor</option>
<option value="69">WOW US / Dragonblight</option>
<option value="70">WOW US / Dragonmaw</option>
<option value="552">WOW US / Drak'Tharon</option>
<option value="474">WOW US / Drak'Tharon</option>
<option value="71">WOW US / Drak'thul</option>
<option value="72">WOW US / Draka</option>
<option value="73">WOW US / Drakkari</option>
<option value="74">WOW US / Dreadmaul</option>
<option value="75">WOW US / Drenden</option>
<option value="76">WOW US / Dunemaul</option>
<option value="77">WOW US / Durotan</option>
<option value="78">WOW US / Duskwood</option>
<option value="79">WOW US / Earthen Ring</option>
<option value="80">WOW US / Echo Isles</option>
<option value="81">WOW US / Eitrigg</option>
<option value="82">WOW US / Eldre'Thalas</option>
<option value="83">WOW US / Elune</option>
<option value="84">WOW US / Emerald Dream</option>
<option value="85">WOW US / Eonar</option>
<option value="86">WOW US / Eredar</option>
<option value="87">WOW US / Executus</option>
<option value="88">WOW US / Exodar</option>
<option value="89">WOW US / Farstriders</option>
<option value="90">WOW US / Feathermoon</option>
<option value="91">WOW US / Fenris</option>
<option value="92">WOW US / Firetree</option>
<option value="475">WOW US / Fizzcrank</option>
<option value="93">WOW US / Frostmane</option>
<option value="94">WOW US / Frostmourne</option>
<option value="95">WOW US / Frostwolf</option>
<option value="476">WOW US / Galakrond</option>
<option value="632">WOW US / Gallywix</option>
<option value="633">WOW US / Gallywix</option>
<option value="96">WOW US / Garithos</option>
<option value="97">WOW US / Garona</option>
<option value="482">WOW US / Garrosh</option>
<option value="98">WOW US / Ghostlands</option>
<option value="99">WOW US / Gilneas</option>
<option value="100">WOW US / Gnomeregan</option>
<option value="631">WOW US / Goldrinn</option>
<option value="101">WOW US / Gorefiend</option>
<option value="102">WOW US / Gorgonnash</option>
<option value="103">WOW US / Greymane</option>
<option value="477">WOW US / Grizzly Hills</option>
<option value="104">WOW US / Gul'dan</option>
<option value="479">WOW US / Gundrak</option>
<option value="105">WOW US / Gurubashi</option>
<option value="106">WOW US / Hakkar</option>
<option value="107">WOW US / Haomarush</option>
<option value="108">WOW US / Hellscream</option>
<option value="109">WOW US / Hydraxis</option>
<option value="110">WOW US / Hyjal</option>
<option value="111">WOW US / Icecrown</option>
<option value="112">WOW US / Illidan</option>
<option value="113">WOW US / Jaedenar</option>
<option value="114">WOW US / Jubei'Thos</option>
<option value="115">WOW US / Kael'thas</option>
<option value="116">WOW US / Kalecgos</option>
<option value="117">WOW US / Kargath</option>
<option value="118">WOW US / Kel'Thuzad</option>
<option value="119">WOW US / Khadgar</option>
<option value="120">WOW US / Khaz Modan</option>
<option value="121">WOW US / Khaz'goroth</option>
<option value="122">WOW US / Kil'Jaeden</option>
<option value="123">WOW US / Kilrogg</option>
<option value="124">WOW US / Kirin Tor</option>
<option value="125">WOW US / Korgath</option>
<option value="126">WOW US / Korialstrasz</option>
<option value="127">WOW US / Kul Tiras</option>
<option value="128">WOW US / Laughing Skull</option>
<option value="129">WOW US / Lethon</option>
<option value="130">WOW US / Lightbringer</option>
<option value="131">WOW US / Lightning's Blade</option>
<option value="132">WOW US / Lightninghoof</option>
<option value="133">WOW US / Llane</option>
<option value="134">WOW US / Lothar</option>
<option value="135">WOW US / Madoran</option>
<option value="136">WOW US / Maelstrom</option>
<option value="137">WOW US / Magtheridon</option>
<option value="138">WOW US / Maiev</option>
<option value="139">WOW US / Mal'Ganis</option>
<option value="140">WOW US / Malfurion</option>
<option value="141">WOW US / Malorne</option>
<option value="142">WOW US / Malygos</option>
<option value="143">WOW US / Mannoroth</option>
<option value="144">WOW US / Medivh</option>
<option value="145">WOW US / Misha</option>
<option value="146">WOW US / Mok'Nathal</option>
<option value="147">WOW US / Moon Guard</option>
<option value="148">WOW US / Moonrunner</option>
<option value="149">WOW US / Mug'thol</option>
<option value="150">WOW US / Muradin</option>
<option value="151">WOW US / Nagrand</option>
<option value="152">WOW US / Nathrezim</option>
<option value="153">WOW US / Nazgrel</option>
<option value="154">WOW US / Nazjatar</option>
<option value="638">WOW US / Nemesis</option>
<option value="155">WOW US / Ner'zhul</option>
<option value="485">WOW US / Nesingwary</option>
<option value="486">WOW US / Nesingwary</option>
<option value="156">WOW US / Nordrassil</option>
<option value="157">WOW US / Norgannon</option>
<option value="158">WOW US / Onyxia</option>
<option value="159">WOW US / Perenolde</option>
<option value="160">WOW US / Proudmoore</option>
<option value="161">WOW US / Quel'dorei</option>
<option value="162">WOW US / Quel'Thalas</option>
<option value="163">WOW US / Ragnaros</option>
<option value="164">WOW US / Ravencrest</option>
<option value="165">WOW US / Ravenholdt</option>
<option value="166">WOW US / Rexxar</option>
<option value="167">WOW US / Rivendare</option>
<option value="168">WOW US / Runetotem</option>
<option value="169">WOW US / Sargeras</option>
<option value="480">WOW US / Saurfang</option>
<option value="170">WOW US / Scarlet Crusade</option>
<option value="171">WOW US / Scilla</option>
<option value="172">WOW US / Sen'Jin</option>
<option value="173">WOW US / Sentinels</option>
<option value="174">WOW US / Shadow Council</option>
<option value="175">WOW US / Shadowmoon</option>
<option value="176">WOW US / Shadowsong</option>
<option value="177">WOW US / Shandris</option>
<option value="178">WOW US / Shattered Halls</option>
<option value="179">WOW US / Shattered Hand</option>
<option value="180">WOW US / Shu'halo</option>
<option value="181">WOW US / Silver Hand</option>
<option value="182">WOW US / Silvermoon</option>
<option value="183">WOW US / Sisters of Elune</option>
<option value="184">WOW US / Skullcrusher</option>
<option value="185">WOW US / Skywall</option>
<option value="186">WOW US / Smolderthorn</option>
<option value="187">WOW US / Spinebreaker</option>
<option value="188">WOW US / Spirestone</option>
<option value="189">WOW US / Staghelm</option>
<option value="190">WOW US / Steamwheedle Cartel</option>
<option value="191">WOW US / Stonemaul</option>
<option value="192">WOW US / Stormrage</option>
<option value="193">WOW US / Stormreaver</option>
<option value="194">WOW US / Stormscale</option>
<option value="195">WOW US / Suramar</option>
<option value="196">WOW US / Tanaris</option>
<option value="197">WOW US / Terenas</option>
<option value="198">WOW US / Terokkar</option>
<option value="199">WOW US / Thaurissan</option>
<option value="200">WOW US / The Forgotten Coast</option>
<option value="201">WOW US / The Scryers</option>
<option value="202">WOW US / The Underbog</option>
<option value="203">WOW US / The Venture Co</option>
<option value="204">WOW US / Thorium Brotherhood</option>
<option value="205">WOW US / Thrall</option>
<option value="206">WOW US / Thunderhorn</option>
<option value="207">WOW US / Thunderlord</option>
<option value="208">WOW US / Tichondrius</option>
<option value="209">WOW US / Tortheldrin</option>
<option value="210">WOW US / Trollbane</option>
<option value="211">WOW US / Turalyon</option>
<option value="212">WOW US / Twisting Nether</option>
<option value="213">WOW US / Uldaman</option>
<option value="214">WOW US / Uldum</option>
<option value="215">WOW US / Undermine</option>
<option value="216">WOW US / Ursin</option>
<option value="217">WOW US / Uther</option>
<option value="218">WOW US / Vashj</option>
<option value="219">WOW US / Vek'nilash</option>
<option value="220">WOW US / Velen</option>
<option value="221">WOW US / Warsong</option>
<option value="222">WOW US / Whisperwind</option>
<option value="223">WOW US / WildHammer</option>
<option value="224">WOW US / Windrunner</option>
<option value="553">WOW US / Winterhoof</option>
<option value="484">WOW US / Wyrmrest Accord</option>
<option value="225">WOW US / Ysera</option>
<option value="226">WOW US / Ysondre</option>
<option value="227">WOW US / Zangarmarsh</option>
<option value="228">WOW US / Zul'jin</option>
<option value="229">WOW US / Zuluhed</option>
<option value="338">WOW EU / Aegwynn</option>
<option value="230">WOW EU / Aerie Peak</option>
<option value="231">WOW EU / Agamaggan</option>
<option value="634">WOW EU / Aggra (Português)</option>
<option value="232">WOW EU / Aggramar</option>
<option value="233">WOW EU / Ahn'Qiraj</option>
<option value="234">WOW EU / Al'Akir</option>
<option value="339">WOW EU / Alexstrasza</option>
<option value="340">WOW EU / Alleria</option>
<option value="235">WOW EU / Alonsus</option>
<option value="341">WOW EU / Aman'Thul</option>
<option value="342">WOW EU / Ambossar</option>
<option value="236">WOW EU / Anachronos</option>
<option value="343">WOW EU / Anetheron</option>
<option value="344">WOW EU / Antonidas</option>
<option value="345">WOW EU / Anub'arak</option>
<option value="421">WOW EU / Arak-arahm</option>
<option value="422">WOW EU / Arathi</option>
<option value="237">WOW EU / Arathor</option>
<option value="423">WOW EU / Archimonde</option>
<option value="238">WOW EU / Argent Dawn</option>
<option value="346">WOW EU / Arthas</option>
<option value="347">WOW EU / Arygos</option>
<option value="239">WOW EU / Aszune</option>
<option value="240">WOW EU / Auchindoun</option>
<option value="241">WOW EU / Azjol-Nerub</option>
<option value="348">WOW EU / Azshara</option>
<option value="686">WOW EU / Azuremyst</option>
<option value="349">WOW EU / Baelgun</option>
<option value="242">WOW EU / Balnazzar</option>
<option value="350">WOW EU / Blackhand</option>
<option value="351">WOW EU / Blackmoore</option>
<option value="352">WOW EU / Blackrock</option>
<option value="243">WOW EU / Blade's Edge</option>
<option value="244">WOW EU / Bladefist</option>
<option value="245">WOW EU / Bloodfeather</option>
<option value="246">WOW EU / Bloodhoof</option>
<option value="247">WOW EU / Bloodscalp</option>
<option value="353">WOW EU / Blutkessel</option>
<option value="248">WOW EU / Boulderfist</option>
<option value="249">WOW EU / Bronze Dragonflight</option>
<option value="250">WOW EU / Bronzebeard</option>
<option value="251">WOW EU / Burning Blade</option>
<option value="252">WOW EU / Burning Legion</option>
<option value="253">WOW EU / Burning Steppes</option>
<option value="458">WOW EU / C'Thun</option>
<option value="488">WOW EU / Chamber of Aspects</option>
<option value="424">WOW EU / Chants éternels</option>
<option value="425">WOW EU / Cho'gall</option>
<option value="254">WOW EU / Chromaggus</option>
<option value="426">WOW EU / Confrérie du Thorium</option>
<option value="427">WOW EU / Conseil des Ombres</option>
<option value="255">WOW EU / Crushridge</option>
<option value="428">WOW EU / Culte de la Rive noire</option>
<option value="256">WOW EU / Daggerspine</option>
<option value="429">WOW EU / Dalaran</option>
<option value="354">WOW EU / Dalvengyr</option>
<option value="257">WOW EU / Darkmoon Faire</option>
<option value="258">WOW EU / Darksorrow</option>
<option value="259">WOW EU / Darkspear</option>
<option value="355">WOW EU / Das Konsortium</option>
<option value="356">WOW EU / Das Syndikat</option>
<option value="489">WOW EU / Dawnbringer</option>
<option value="260">WOW EU / Deathwing</option>
<option value="261">WOW EU / Defias Brotherhood</option>
<option value="262">WOW EU / Dentarg</option>
<option value="357">WOW EU / Der abyssische Rat</option>
<option value="358">WOW EU / Der Mithrilorden</option>
<option value="359">WOW EU / Der Rat von Dalaran</option>
<option value="360">WOW EU / Destromath</option>
<option value="361">WOW EU / Dethecus</option>
<option value="362">WOW EU / Die Aldor</option>
<option value="363">WOW EU / Die Arguswacht</option>
<option value="364">WOW EU / Die ewige Wacht</option>
<option value="365">WOW EU / Die Nachtwache</option>
<option value="366">WOW EU / Die Silberne Hand</option>
<option value="367">WOW EU / Die Todeskrallen</option>
<option value="263">WOW EU / Doomhammer</option>
<option value="264">WOW EU / Draenor</option>
<option value="265">WOW EU / Dragonblight</option>
<option value="266">WOW EU / Dragonmaw</option>
<option value="267">WOW EU / Drak'thul</option>
<option value="430">WOW EU / Drek'Thar</option>
<option value="459">WOW EU / Dun Modr</option>
<option value="368">WOW EU / Dun Morogh</option>
<option value="268">WOW EU / Dunemaul</option>
<option value="369">WOW EU / Durotan</option>
<option value="269">WOW EU / Earthen Ring</option>
<option value="370">WOW EU / Echsenkessel</option>
<option value="431">WOW EU / Eitrigg</option>
<option value="432">WOW EU / Eldre'Thalas</option>
<option value="433">WOW EU / Elune</option>
<option value="270">WOW EU / Emerald Dream</option>
<option value="271">WOW EU / Emeriss</option>
<option value="272">WOW EU / Eonar</option>
<option value="371">WOW EU / Eredar</option>
<option value="273">WOW EU / Executus</option>
<option value="460">WOW EU / Exodar</option>
<option value="372">WOW EU / Festung der Stürme</option>
<option value="373">WOW EU / Forscherliga</option>
<option value="274">WOW EU / Frostmane</option>
<option value="374">WOW EU / Frostmourne</option>
<option value="275">WOW EU / Frostwhisper</option>
<option value="375">WOW EU / Frostwolf</option>
<option value="434">WOW EU / Garona</option>
<option value="276">WOW EU / Genjuros</option>
<option value="277">WOW EU / Ghostlands</option>
<option value="376">WOW EU / Gilneas</option>
<option value="377">WOW EU / Gorgonnash</option>
<option value="278">WOW EU / Grim Batol</option>
<option value="378">WOW EU / Gul'dan</option>
<option value="279">WOW EU / Hakkar</option>
<option value="280">WOW EU / Haomarush</option>
<option value="281">WOW EU / Hellfire</option>
<option value="282">WOW EU / Hellscream</option>
<option value="435">WOW EU / Hyjal</option>
<option value="436">WOW EU / Illidan</option>
<option value="283">WOW EU / Jaedenar</option>
<option value="437">WOW EU / Kael'thas</option>
<option value="284">WOW EU / Karazhan</option>
<option value="379">WOW EU / Kargath</option>
<option value="285">WOW EU / Kazzak</option>
<option value="380">WOW EU / Kel'Thuzad</option>
<option value="286">WOW EU / Khadgar</option>
<option value="438">WOW EU / Khaz Modan</option>
<option value="381">WOW EU / Khaz'goroth</option>
<option value="382">WOW EU / Kil'Jaeden</option>
<option value="287">WOW EU / Kilrogg</option>
<option value="439">WOW EU / Kirin Tor</option>
<option value="288">WOW EU / Kor'gall</option>
<option value="383">WOW EU / Krag'jin</option>
<option value="440">WOW EU / Krasus</option>
<option value="289">WOW EU / Kul Tiras</option>
<option value="384">WOW EU / Kult der Verdammten</option>
<option value="441">WOW EU / La Croisade écarlate</option>
<option value="290">WOW EU / Laughing Skull</option>
<option value="442">WOW EU / Les Clairvoyants</option>
<option value="443">WOW EU / Les Sentinelles</option>
<option value="291">WOW EU / Lightbringer</option>
<option value="292">WOW EU / Lightning's Blade</option>
<option value="385">WOW EU / Lordaeron</option>
<option value="461">WOW EU / Los Errantes</option>
<option value="386">WOW EU / Lothar</option>
<option value="387">WOW EU / Madmortem</option>
<option value="293">WOW EU / Magtheridon</option>
<option value="388">WOW EU / Mal'Ganis</option>
<option value="389">WOW EU / Malfurion</option>
<option value="390">WOW EU / Malygos</option>
<option value="391">WOW EU / Mannoroth</option>
<option value="444">WOW EU / Marécage de Zangar</option>
<option value="294">WOW EU / Mazrigos</option>
<option value="445">WOW EU / Medivh</option>
<option value="462">WOW EU / Minahonda</option>
<option value="295">WOW EU / Molten Core</option>
<option value="296">WOW EU / Moonglade</option>
<option value="392">WOW EU / Mug'thol</option>
<option value="297">WOW EU / Nagrand</option>
<option value="393">WOW EU / Nathrezim</option>
<option value="446">WOW EU / Naxxramas</option>
<option value="394">WOW EU / Nazjatar</option>
<option value="395">WOW EU / Nefarian</option>
<option value="684">WOW EU / Nemesis</option>
<option value="298">WOW EU / Neptulon</option>
<option value="447">WOW EU / Ner'zhul</option>
<option value="396">WOW EU / Nera'thor</option>
<option value="397">WOW EU / Nethersturm</option>
<option value="299">WOW EU / Nordrassil</option>
<option value="398">WOW EU / Norgannon</option>
<option value="399">WOW EU / Nozdormu</option>
<option value="400">WOW EU / Onyxia</option>
<option value="300">WOW EU / Outland</option>
<option value="401">WOW EU / Perenolde</option>
<option value="685">WOW EU / Pozzo dell'Eternità</option>
<option value="402">WOW EU / Proudmoore</option>
<option value="301">WOW EU / Quel'Thalas</option>
<option value="302">WOW EU / Ragnaros</option>
<option value="403">WOW EU / Rajaxx</option>
<option value="448">WOW EU / Rashgarroth</option>
<option value="303">WOW EU / Ravencrest</option>
<option value="304">WOW EU / Ravenholdt</option>
<option value="404">WOW EU / Rexxar</option>
<option value="305">WOW EU / Runetotem</option>
<option value="636">WOW EU / sanguino</option>
<option value="449">WOW EU / Sargeras</option>
<option value="487">WOW EU / Saurfang</option>
<option value="306">WOW EU / Scarshield Legion</option>
<option value="405">WOW EU / Sen'jin</option>
<option value="307">WOW EU / Shadowmoon</option>
<option value="308">WOW EU / Shadowsong</option>
<option value="309">WOW EU / Shattered Halls</option>
<option value="310">WOW EU / Shattered Hand</option>
<option value="406">WOW EU / Shattrath</option>
<option value="463">WOW EU / Shen'dralar</option>
<option value="311">WOW EU / Silvermoon</option>
<option value="450">WOW EU / Sinstralis</option>
<option value="312">WOW EU / Skullcrusher</option>
<option value="313">WOW EU / Spinebreaker</option>
<option value="629">WOW EU / Sporeggar</option>
<option value="314">WOW EU / Steamwheedle Cartel</option>
<option value="315">WOW EU / Stonemaul</option>
<option value="316">WOW EU / Stormrage</option>
<option value="317">WOW EU / Stormreaver</option>
<option value="318">WOW EU / Stormscale</option>
<option value="319">WOW EU / Sunstrider</option>
<option value="451">WOW EU / Suramar</option>
<option value="320">WOW EU / Sylvanas</option>
<option value="407">WOW EU / Taerar</option>
<option value="321">WOW EU / Talnivarr</option>
<option value="322">WOW EU / Tarren Mill</option>
<option value="408">WOW EU / Teldrassil</option>
<option value="452">WOW EU / Temple noir</option>
<option value="323">WOW EU / Terenas</option>
<option value="637">WOW EU / terokkar</option>
<option value="409">WOW EU / Terrordar</option>
<option value="324">WOW EU / The Maelstrom</option>
<option value="325">WOW EU / The Sha'tar</option>
<option value="326">WOW EU / The Venture Co</option>
<option value="410">WOW EU / Theradras</option>
<option value="411">WOW EU / Thrall</option>
<option value="453">WOW EU / Throk'Feroth</option>
<option value="327">WOW EU / Thunderhorn</option>
<option value="412">WOW EU / Tichondrius</option>
<option value="413">WOW EU / Tirion</option>
<option value="414">WOW EU / Todeswache</option>
<option value="328">WOW EU / Trollbane</option>
<option value="329">WOW EU / Turalyon</option>
<option value="330">WOW EU / Twilight's Hammer</option>
<option value="331">WOW EU / Twisting Nether</option>
<option value="464">WOW EU / Tyrande</option>
<option value="454">WOW EU / Uldaman</option>
<option value="687">WOW EU / ulduar</option>
<option value="465">WOW EU / Uldum</option>
<option value="415">WOW EU / Un'Goro</option>
<option value="455">WOW EU / Varimathras</option>
<option value="332">WOW EU / Vashj</option>
<option value="416">WOW EU / Vek'lor</option>
<option value="333">WOW EU / Vek'nilash</option>
<option value="456">WOW EU / Vol'jin</option>
<option value="334">WOW EU / Warsong</option>
<option value="335">WOW EU / Wildhammer</option>
<option value="483">WOW EU / Winterhoof</option>
<option value="417">WOW EU / Wrathbringer</option>
<option value="336">WOW EU / Xavius</option>
<option value="418">WOW EU / Ysera</option>
<option value="457">WOW EU / Ysondre</option>
<option value="337">WOW EU / Zenedar</option>
<option value="419">WOW EU / Zirkel des Cenarius</option>
<option value="466">WOW EU / Zul'Jin</option>
<option value="420">WOW EU / Zuluhed</option>
<option value="467">WOW EU / Азурегос</option>
<option value="468">WOW EU / Вечная Песня</option>
<option value="469">WOW EU / Гордунни</option>
<option value="470">WOW EU / Пиратская бухта</option>
<option value="471">WOW EU / Термоштепсель</option>
<option value="472">WOW EU / Ясеневый лес</option>